import { fillBox, keyFor } from './csgBuilder.js';

export class AStarPathfinder {
  constructor(buildSpec, materials) {
    this.spec = buildSpec;
    this.materials = materials;
  }

  connect(shell, layout, plannerJson) {
    const mainBox = shell.volumeBoxes.find((box) => box.id === 'main') || shell.volumeBoxes[0];
    const mainDoor = this.carveMainDoor(shell.grid, mainBox);
    const openedEdges = this.openTopologyEdges(shell.grid, layout.rooms, plannerJson.edges || [], mainBox);
    const { stairs, floorOpenings } = this.addStairs(shell.grid, mainBox);
    layout.floorOpenings.push(...floorOpenings);

    return {
      mainDoor,
      openedEdges,
      stairs,
      floorOpenings,
      pathfinder: {
        algorithm: 'A*',
        openedDoorCount: openedEdges.length + 1,
        stairCount: stairs.length,
        note: 'Door and stair coordinates are generated by local JavaScript pathfinding, not by LLM.'
      }
    };
  }

  carveMainDoor(grid, mainBox) {
    const side = String(this.spec.door_side || 'south');
    const width = Number(this.spec.door_width || 2);
    const height = Number(this.spec.door_height || 3);
    const centerX = Math.floor((mainBox.min_x + mainBox.max_x) / 2);
    const centerZ = Math.floor((mainBox.min_z + mainBox.max_z) / 2);

    if (['south', 'north'].includes(side)) {
      const z = side === 'south' ? mainBox.max_z : mainBox.min_z;
      const startX = centerX - Math.floor(width / 2);
      for (let i = 0; i < width; i += 1) {
        const x = startX + i;
        for (let dy = 0; dy < height; dy += 1) grid.delete(keyFor(x, 1 + dy, z));
        const hinge = width > 1 && i === width - 1 ? 'right' : 'left';
        grid.set(keyFor(x, 1, z), cell(doorState(this.materials.door, side, 'lower', hinge), 'door'));
        grid.set(keyFor(x, 2, z), cell(doorState(this.materials.door, side, 'upper', hinge), 'door'));
      }
      const outsideZ = z + (side === 'south' ? 1 : -1);
      fillBox(grid, startX - 1, 0, outsideZ, startX + width, 0, outsideZ, this.materials.path || 'minecraft:gravel', 'door');
      return { side, x: startX, z, width, height, doorBlock: doorState(this.materials.door, side, 'lower', 'left') };
    }

    const x = side === 'east' ? mainBox.max_x : mainBox.min_x;
    const startZ = centerZ - Math.floor(width / 2);
    for (let i = 0; i < width; i += 1) {
      const z = startZ + i;
      for (let dy = 0; dy < height; dy += 1) grid.delete(keyFor(x, 1 + dy, z));
      const hinge = width > 1 && i === width - 1 ? 'right' : 'left';
      grid.set(keyFor(x, 1, z), cell(doorState(this.materials.door, side, 'lower', hinge), 'door'));
      grid.set(keyFor(x, 2, z), cell(doorState(this.materials.door, side, 'upper', hinge), 'door'));
    }
    const outsideX = x + (side === 'east' ? 1 : -1);
    fillBox(grid, outsideX, 0, startZ - 1, outsideX, 0, startZ + width, this.materials.path || 'minecraft:gravel', 'door');
    return { side, x, z: startZ, width, height, doorBlock: doorState(this.materials.door, side, 'lower', 'left') };
  }

  openTopologyEdges(grid, rooms, edges, mainBox) {
    const roomById = new Map(rooms.map((room) => [room.id, room]));
    const opened = [];
    for (const edge of edges) {
      const a = roomById.get(edge.from);
      const b = roomById.get(edge.to);
      if (!a || !b || a.floor !== b.floor) continue;
      const y = Math.min(a.min_y, b.min_y);
      const path = aStar2d(center(a), center(b), {
        minX: mainBox.min_x + 1,
        maxX: mainBox.max_x - 1,
        minZ: mainBox.min_z + 1,
        maxZ: mainBox.max_z - 1
      }, (x, z) => (grid.get(keyFor(x, y, z))?.module === 'interior' ? 6 : 1));
      let carved = 0;
      for (const point of path) {
        if (grid.get(keyFor(point.x, y, point.z))?.module !== 'interior') continue;
        for (let dy = 0; dy < 3; dy += 1) grid.delete(keyFor(point.x, y + dy, point.z));
        carved += 1;
      }
      if (carved) opened.push({ from: edge.from, to: edge.to, floor: a.floor, carvedCells: carved });
    }
    return opened;
  }

  addStairs(grid, mainBox) {
    if (this.spec.floors <= 1) return { stairs: [], floorOpenings: [] };
    const stairs = [];
    const floorOpenings = [];
    const startX = mainBox.min_x + 3;
    const startZ = mainBox.max_z - 3;
    const stairBlock = stairState(this.materials.stairs, 'north');

    for (let floor = 0; floor < this.spec.floors - 1; floor += 1) {
      const openingY = (floor + 1) * this.spec.floor_height + 1;
      const opening = {
        floor: floor + 1,
        min_x: startX - 1,
        max_x: startX + 2,
        y: openingY,
        min_z: startZ - this.spec.floor_height - 1,
        max_z: startZ + 1
      };
      floorOpenings.push(opening);
      fillBox(grid, opening.min_x, opening.y, opening.min_z, opening.max_x, opening.y, opening.max_z, 'minecraft:air', 'stairs');
      for (let step = 0; step < this.spec.floor_height; step += 1) {
        const y = floor * this.spec.floor_height + 2 + step;
        const z = startZ - step;
        for (let dx = 0; dx < 2; dx += 1) grid.set(keyFor(startX + dx, y, z), cell(stairBlock, 'stairs'));
        stairs.push({ floor, step, x: startX, y, z });
      }
    }
    return { stairs, floorOpenings };
  }
}

function aStar2d(start, goal, bounds, cost) {
  const frontier = [{ priority: 0, point: start }];
  const cameFrom = new Map([[pointKey(start), null]]);
  const gScore = new Map([[pointKey(start), 0]]);

  while (frontier.length) {
    frontier.sort((a, b) => a.priority - b.priority);
    const current = frontier.shift().point;
    if (current.x === goal.x && current.z === goal.z) break;
    for (const next of neighbors(current, bounds)) {
      const nextKey = pointKey(next);
      const currentScore = gScore.get(pointKey(current));
      const nextCost = currentScore + cost(next.x, next.z);
      if (!gScore.has(nextKey) || nextCost < gScore.get(nextKey)) {
        gScore.set(nextKey, nextCost);
        frontier.push({ priority: nextCost + Math.abs(goal.x - next.x) + Math.abs(goal.z - next.z), point: next });
        cameFrom.set(nextKey, current);
      }
    }
  }

  if (!cameFrom.has(pointKey(goal))) return [];
  const path = [];
  let current = goal;
  while (current) {
    path.push(current);
    current = cameFrom.get(pointKey(current));
  }
  return path.reverse();
}

function neighbors(point, bounds) {
  return [
    { x: point.x + 1, z: point.z },
    { x: point.x - 1, z: point.z },
    { x: point.x, z: point.z + 1 },
    { x: point.x, z: point.z - 1 }
  ].filter((item) => item.x >= bounds.minX && item.x <= bounds.maxX && item.z >= bounds.minZ && item.z <= bounds.maxZ);
}

function center(room) {
  return {
    x: Math.floor((room.min_x + room.max_x) / 2),
    z: Math.floor((room.min_z + room.max_z) / 2)
  };
}

function pointKey(point) {
  return `${point.x},${point.z}`;
}

function doorState(block = 'minecraft:dark_oak_door', facing, half, hinge) {
  let base = String(block).split('[')[0];
  if (!base.endsWith('_door')) base = 'minecraft:dark_oak_door';
  return `${base}[facing=${facing},half=${half},hinge=${hinge}]`;
}

function stairState(block = 'minecraft:spruce_stairs', facing) {
  let base = String(block).split('[')[0];
  if (!base.includes('stairs')) base = 'minecraft:spruce_stairs';
  return `${base}[facing=${facing},half=bottom]`;
}

function cell(block, module) {
  return { block, module };
}
