import { fillBox, keyFor } from './csgBuilder.js';

export class AStarPathfinder {
  constructor(buildSpec, materials) {
    this.spec = buildSpec;
    this.materials = materials;
  }

  connect(shell, layout, plannerJson = {}, openingPlan = {}) {
    const mainBox = shell.volumeBoxes.find((box) => box.id === 'main') || shell.volumeBoxes[0];
    const rooms = Array.isArray(layout.rooms) ? layout.rooms : [];
    const existingDoors = Array.isArray(layout.interiorDoors) ? layout.interiorDoors : [];
    const mainDoor = this.carveMainDoor(shell.grid, mainBox, rooms, openingPlan);
    const openedEdges = this.openTopologyEdges(shell.grid, rooms, plannerJson.edges || [], shell, existingDoors);
    const { stairs, floorOpenings, stairCoreRoom } = this.addStairs(shell.grid, mainBox, rooms, plannerJson);
    layout.floorOpenings.push(...floorOpenings);

    const attachedDoorCount = existingDoors.filter((door) => door.kind === 'attached-volume').length;
    const failedEdgeCount = openedEdges.filter((edge) => edge.status === 'unreachable').length;
    const routedEdgeCount = openedEdges.filter((edge) => edge.status === 'routed').length;

    return {
      mainDoor,
      openedEdges,
      stairs,
      floorOpenings,
      pathfinder: {
        algorithm: 'A*',
        openedDoorCount: openedEdges.filter((edge) => edge.carvedCells > 0).length + attachedDoorCount + 1,
        routedEdgeCount,
        failedEdgeCount,
        attachedDoorCount,
        stairCount: stairs.length,
        stairCoreRoom: stairCoreRoom?.id || 'fallback-corner',
        plannedOpeningCount: Number(openingPlan.engine_hints?.planned_opening_count || 0),
        openingStrategy: openingPlan.main_entry?.strategy || 'direct-entry',
        note: 'Door and stair coordinates are generated by local JavaScript pathfinding, not by LLM.'
      }
    };
  }

  carveMainDoor(grid, mainBox, rooms = [], openingPlan = {}) {
    const side = String(openingPlan.main_entry?.side || this.spec.door_side || 'south');
    const width = clampInt(openingPlan.main_entry?.width || this.spec.door_width || 2, 1, 4);
    const height = clampInt(openingPlan.main_entry?.height || this.spec.door_height || 3, 2, 6);
    const thickness = clampInt(this.spec.shell_thickness || 1, 1, 3);
    const approachLength = exteriorApproachLength(this.spec);
    const targetRoom = selectEntryRoom(rooms, mainBox, side, thickness, openingPlan.main_entry?.target_room);
    const target = targetRoom ? center(targetRoom) : centerBox(mainBox);

    if (['south', 'north'].includes(side)) {
      const boundaryZ = side === 'south' ? mainBox.max_z : mainBox.min_z;
      const insideStep = side === 'south' ? -1 : 1;
      const startX = clampInt(target.x - Math.floor(width / 2), mainBox.min_x + 1, mainBox.max_x - width);
      for (let i = 0; i < width; i += 1) {
        const x = startX + i;
        for (let depth = 0; depth < thickness; depth += 1) {
          const z = boundaryZ + insideStep * depth;
          for (let dy = 0; dy < height; dy += 1) grid.delete(keyFor(x, 1 + dy, z));
        }
        const hinge = width > 1 && i === width - 1 ? 'right' : 'left';
        grid.set(keyFor(x, 1, boundaryZ), cell(doorState(this.materials.door, side, 'lower', hinge), 'door'));
        grid.set(keyFor(x, 2, boundaryZ), cell(doorState(this.materials.door, side, 'upper', hinge), 'door'));
      }
      const outsideZ = boundaryZ + (side === 'south' ? 1 : -1);
      const approach = fillExteriorApproach(grid, this.materials, side, startX - 1, startX + width, outsideZ, approachLength);
      return {
        side,
        x: startX,
        z: boundaryZ,
        width,
        height,
        targetRoom: targetRoom?.id,
        throughThickness: thickness,
        approachLength: approach.length,
        approach,
        doorBlock: doorState(this.materials.door, side, 'lower', 'left')
      };
    }

    const boundaryX = side === 'east' ? mainBox.max_x : mainBox.min_x;
    const insideStep = side === 'east' ? -1 : 1;
    const startZ = clampInt(target.z - Math.floor(width / 2), mainBox.min_z + 1, mainBox.max_z - width);
    for (let i = 0; i < width; i += 1) {
      const z = startZ + i;
      for (let depth = 0; depth < thickness; depth += 1) {
        const x = boundaryX + insideStep * depth;
        for (let dy = 0; dy < height; dy += 1) grid.delete(keyFor(x, 1 + dy, z));
      }
      const hinge = width > 1 && i === width - 1 ? 'right' : 'left';
      grid.set(keyFor(boundaryX, 1, z), cell(doorState(this.materials.door, side, 'lower', hinge), 'door'));
      grid.set(keyFor(boundaryX, 2, z), cell(doorState(this.materials.door, side, 'upper', hinge), 'door'));
    }
    const outsideX = boundaryX + (side === 'east' ? 1 : -1);
    const approach = fillExteriorApproach(grid, this.materials, side, startZ - 1, startZ + width, outsideX, approachLength);
    return {
      side,
      x: boundaryX,
      z: startZ,
      width,
      height,
      targetRoom: targetRoom?.id,
      throughThickness: thickness,
      approachLength: approach.length,
      approach,
      doorBlock: doorState(this.materials.door, side, 'lower', 'left')
    };
  }

  openTopologyEdges(grid, rooms, edges, shell, existingDoors = []) {
    const roomById = new Map(rooms.map((room) => [room.id, room]));
    const opened = [];
    const existingDoorPairs = new Set(existingDoors.flatMap((door) => pairKeys(door.connects || [])));

    for (const edge of edges) {
      const a = roomById.get(edge.from);
      const b = roomById.get(edge.to);
      if (!a || !b) {
        opened.push({ from: edge.from, to: edge.to, floor: undefined, status: 'missing-room', carvedCells: 0, pathLength: 0 });
        continue;
      }
      if (a.floor !== b.floor) {
        opened.push({ from: edge.from, to: edge.to, floor: a.floor, relation: edge.relation, priority: edge.priority, status: 'vertical-edge', carvedCells: 0, pathLength: 0 });
        continue;
      }

      const y = Math.min(a.min_y, b.min_y);
      const start = center(a);
      const goal = center(b);
      const bounds = routeBoundsForRooms(a, b, shell.bounds);
      const path = aStar2d(start, goal, bounds, (x, z) => routeCost(grid, x, y, z, a, b));
      if (!path.length) {
        opened.push({ from: edge.from, to: edge.to, floor: a.floor, status: 'unreachable', carvedCells: 0, pathLength: 0 });
        continue;
      }

      let carved = 0;
      for (const point of path) {
        const item = grid.get(keyFor(point.x, y, point.z));
        if (item?.module !== 'interior') continue;
        for (let dy = 0; dy < 3; dy += 1) grid.delete(keyFor(point.x, y + dy, point.z));
        carved += 1;
      }

      opened.push({
        from: edge.from,
        to: edge.to,
        floor: a.floor,
        relation: edge.relation,
        priority: edge.priority,
        status: 'routed',
        carvedCells: carved,
        pathLength: path.length,
        usesExistingDoor: existingDoorPairs.has(pairKey(edge.from, edge.to))
      });
    }

    return opened;
  }

  addStairs(grid, mainBox, rooms = [], plannerJson = {}) {
    if (this.spec.floors <= 1) return { stairs: [], floorOpenings: [], stairCoreRoom: undefined };
    const stairs = [];
    const floorOpenings = [];
    const stairCoreRoom = selectStairCoreRoom(rooms, plannerJson, this.spec);
    const anchor = stairAnchor(stairCoreRoom, mainBox, this.spec);
    const stairBlock = stairState(this.materials.stairs, anchor.facing);
    const floorBlock = this.materials.floor || 'minecraft:spruce_planks';

    for (let floor = 0; floor < this.spec.floors - 1; floor += 1) {
      const openingY = (floor + 1) * this.spec.floor_height + 1;
      const opening = openingForAnchor(anchor, floor + 1, openingY, stairCoreRoom);
      floorOpenings.push(opening);
      fillBox(grid, opening.min_x, opening.y, opening.min_z, opening.max_x, opening.y, opening.max_z, 'minecraft:air', 'stairs');
      for (let step = 0; step < this.spec.floor_height; step += 1) {
        const point = stairPoint(anchor, floor, step, this.spec.floor_height);
        for (const offset of anchor.offsets) {
          const x = point.x + offset.x;
          const z = point.z + offset.z;
          grid.set(keyFor(x, point.y, z), cell(stairBlock, 'stairs'));
          grid.delete(keyFor(x, point.y + 1, z));
        }
        stairs.push({ floor, step, x: point.x, y: point.y, z: point.z, facing: anchor.facing, sourceRoom: stairCoreRoom?.id || 'fallback-corner' });
      }
      placeStairLanding(grid, anchor, openingY, floorBlock);
    }
    return { stairs, floorOpenings, stairCoreRoom };
  }
}

function selectEntryRoom(rooms, mainBox, side = 'south', thickness = 1, preferredId) {
  const groundRooms = rooms.filter((room) => Number(room.floor || 0) === 0);
  const boundaryRooms = groundRooms.filter((room) => roomTouchesBoundary(room, mainBox, side, thickness + 1));
  const preferred = boundaryRooms.find((room) => room.id === preferredId);
  if (preferred) return preferred;

  const candidates = boundaryRooms.length ? boundaryRooms : groundRooms;
  return [...candidates].sort((a, b) => entryRoomScore(b) - entryRoomScore(a))[0];
}

function entryRoomScore(room) {
  let score = 0;
  if (room.id === 'entry') score += 100;
  if (room.type === 'entry') score += 90;
  if (room.access === 'main-door') score += 80;
  if (room.source === 'main') score += 60;
  if (room.zone === 'public') score += 40;
  if (['living', 'great_hall', 'lounge', 'dining'].includes(room.type)) score += 20;
  if (['sunroom', 'greenhouse', 'garage', 'bathroom', 'storage'].includes(room.type)) score -= 20;
  return score;
}

function roomTouchesBoundary(room, mainBox, side, tolerance) {
  if (!mainBox) return true;
  if (side === 'south') return mainBox.max_z >= room.min_z - tolerance && mainBox.max_z <= room.max_z + tolerance;
  if (side === 'north') return mainBox.min_z >= room.min_z - tolerance && mainBox.min_z <= room.max_z + tolerance;
  if (side === 'east') return mainBox.max_x >= room.min_x - tolerance && mainBox.max_x <= room.max_x + tolerance;
  return mainBox.min_x >= room.min_x - tolerance && mainBox.min_x <= room.max_x + tolerance;
}

function selectStairCoreRoom(rooms, plannerJson = {}, spec = {}) {
  const verticalCoreId = plannerJson.circulation_rules?.vertical_core;
  const ranked = [
    rooms.find((room) => room.id === verticalCoreId && room.floor === 0),
    rooms.find((room) => room.type === 'stairs' && room.floor === 0),
    rooms.find((room) => room.tags?.includes('vertical-core') && room.floor === 0),
    rooms.find((room) => room.type === 'corridor' && room.floor === 0),
    rooms.find((room) => room.type === 'entry' && room.floor === 0),
    rooms.find((room) => ['living', 'lounge', 'great_hall'].includes(room.type) && room.floor === 0)
  ].filter(Boolean);
  return ranked.find((room) => roomCanHostStairs(room, spec));
}

function roomCanHostStairs(room, spec = {}) {
  const runLength = clampInt(spec.floor_height || 5, 4, 8);
  const width = Number(room.max_x) - Number(room.min_x) + 1;
  const depth = Number(room.max_z) - Number(room.min_z) + 1;
  return (depth >= runLength && width >= 2) || (width >= runLength && depth >= 2);
}

function stairAnchor(room, mainBox, spec) {
  const fallbackRoom = room || {
    min_x: mainBox.min_x + clampInt(spec.shell_thickness || 1, 1, 3),
    max_x: mainBox.max_x - clampInt(spec.shell_thickness || 1, 1, 3),
    min_z: mainBox.min_z + clampInt(spec.shell_thickness || 1, 1, 3),
    max_z: mainBox.max_z - clampInt(spec.shell_thickness || 1, 1, 3)
  };
  const runLength = clampInt(spec.floor_height || 5, 4, 8);
  const width = fallbackRoom.max_x - fallbackRoom.min_x + 1;
  const depth = fallbackRoom.max_z - fallbackRoom.min_z + 1;
  const minX = fallbackRoom.min_x;
  const maxX = fallbackRoom.max_x;
  const minZ = fallbackRoom.min_z;
  const maxZ = fallbackRoom.max_z;

  if (depth >= runLength && width >= 2) {
    const x = clampInt(minX, minX, Math.max(minX, maxX - 1));
    const startZ = clampInt(maxZ, minZ + runLength - 1, maxZ);
    return {
      axis: 'z',
      facing: 'north',
      start: { x, z: startZ },
      end: { x, z: startZ - runLength + 1 },
      width: 2,
      length: runLength,
      offsets: [{ x: 0, z: 0 }, { x: 1, z: 0 }]
    };
  }

  if (width >= runLength && depth >= 2) {
    const z = clampInt(minZ, minZ, Math.max(minZ, maxZ - 1));
    const startX = clampInt(maxX, minX + runLength - 1, maxX);
    return {
      axis: 'x',
      facing: 'west',
      start: { x: startX, z },
      end: { x: startX - runLength + 1, z },
      width: 2,
      length: runLength,
      offsets: [{ x: 0, z: 0 }, { x: 0, z: 1 }]
    };
  }

  const x = clampInt(Math.floor((minX + maxX) / 2), mainBox.min_x + 2, mainBox.max_x - 3);
  const z = clampInt(mainBox.max_z - 3, mainBox.min_z + runLength, mainBox.max_z - 2);
  return {
    axis: 'z',
    facing: 'north',
    start: { x, z },
    end: { x, z: z - runLength + 1 },
    width: 2,
    length: runLength,
    offsets: [{ x: 0, z: 0 }, { x: 1, z: 0 }]
  };
}

function stairPoint(anchor, floor, step, floorHeight) {
  const y = floor * floorHeight + 2 + step;
  if (anchor.axis === 'x') return { x: anchor.start.x - step, y, z: anchor.start.z };
  return { x: anchor.start.x, y, z: anchor.start.z - step };
}

function openingForAnchor(anchor, floor, y, room) {
  const sourceRoom = room?.id || 'fallback-corner';
  if (anchor.axis === 'x') {
    const x1 = Math.min(anchor.start.x, anchor.end.x);
    const x2 = Math.max(anchor.start.x, anchor.end.x);
    return clampOpeningToRoom({
      floor,
      sourceRoom,
      axis: anchor.axis,
      min_x: x1,
      max_x: x2,
      y,
      min_z: anchor.start.z - 1,
      max_z: anchor.start.z + 2
    }, room);
  }
  const z1 = Math.min(anchor.start.z, anchor.end.z);
  const z2 = Math.max(anchor.start.z, anchor.end.z);
  return clampOpeningToRoom({
    floor,
    sourceRoom,
    axis: anchor.axis,
    min_x: anchor.start.x - 1,
    max_x: anchor.start.x + 2,
    y,
    min_z: z1,
    max_z: z2
  }, room);
}

function clampOpeningToRoom(opening, room) {
  if (!room) return opening;
  return {
    ...opening,
    min_x: Math.max(opening.min_x, room.min_x),
    max_x: Math.min(opening.max_x, room.max_x),
    min_z: Math.max(opening.min_z, room.min_z),
    max_z: Math.min(opening.max_z, room.max_z)
  };
}

function placeStairLanding(grid, anchor, y, floorBlock) {
  for (const point of landingCellsForAnchor(anchor)) {
    grid.set(keyFor(point.x, y, point.z), cell(floorBlock, 'floors'));
    grid.delete(keyFor(point.x, y + 1, point.z));
    grid.delete(keyFor(point.x, y + 2, point.z));
  }
}

function landingCellsForAnchor(anchor) {
  const dx = Math.sign(anchor.end.x - anchor.start.x);
  const dz = Math.sign(anchor.end.z - anchor.start.z);
  const base = {
    x: anchor.end.x + dx,
    z: anchor.end.z + dz
  };
  return anchor.offsets.map((offset) => ({
    x: base.x + offset.x,
    z: base.z + offset.z
  }));
}

function routeBoundsForRooms(a, b, shellBounds = {}) {
  const padding = 3;
  return {
    minX: Math.max(shellBounds.minX ?? -64, Math.min(a.min_x, b.min_x) - padding),
    maxX: Math.min(shellBounds.maxX ?? 64, Math.max(a.max_x, b.max_x) + padding),
    minZ: Math.max(shellBounds.minZ ?? -64, Math.min(a.min_z, b.min_z) - padding),
    maxZ: Math.min(shellBounds.maxZ ?? 64, Math.max(a.max_z, b.max_z) + padding)
  };
}

function routeCost(grid, x, y, z, a, b) {
  if (pointInRoom2d(x, z, a) || pointInRoom2d(x, z, b)) return 1;
  const item = grid.get(keyFor(x, y, z));
  if (!item) return 2;
  if (item.module === 'door' || item.module === 'stairs') return 1;
  if (item.module === 'interior') return 7;
  if (['foundation', 'floors', 'windows', 'skylight'].includes(item.module)) return 3;
  if (['structural_frame', 'bracing', 'retaining_wall', 'foundation_anchor', 'roof_frame'].includes(item.module)) return 32;
  if (['walls', 'wing', 'tower', 'sunroom', 'garage'].includes(item.module)) return 24;
  return 5;
}

function pointInRoom2d(x, z, room) {
  return x >= room.min_x && x <= room.max_x && z >= room.min_z && z <= room.max_z;
}

function aStar2d(start, goal, bounds, cost) {
  const frontier = [{ priority: 0, point: start }];
  const cameFrom = new Map([[pointKey(start), null]]);
  const gScore = new Map([[pointKey(start), 0]]);

  while (frontier.length) {
    frontier.sort((a, b) => a.priority - b.priority);
    const current = frontier.shift().point;
    if (current.x === goal.x && current.z === goal.z) break;
    for (const next of neighbors(current, bounds)) {
      const nextKey = pointKey(next);
      const currentScore = gScore.get(pointKey(current));
      const nextCost = currentScore + cost(next.x, next.z);
      if (!gScore.has(nextKey) || nextCost < gScore.get(nextKey)) {
        gScore.set(nextKey, nextCost);
        frontier.push({ priority: nextCost + Math.abs(goal.x - next.x) + Math.abs(goal.z - next.z), point: next });
        cameFrom.set(nextKey, current);
      }
    }
  }

  if (!cameFrom.has(pointKey(goal))) return [];
  const path = [];
  let current = goal;
  while (current) {
    path.push(current);
    current = cameFrom.get(pointKey(current));
  }
  return path.reverse();
}

function neighbors(point, bounds) {
  return [
    { x: point.x + 1, z: point.z },
    { x: point.x - 1, z: point.z },
    { x: point.x, z: point.z + 1 },
    { x: point.x, z: point.z - 1 }
  ].filter((item) => item.x >= bounds.minX && item.x <= bounds.maxX && item.z >= bounds.minZ && item.z <= bounds.maxZ);
}

function center(room) {
  return {
    x: Math.floor((room.min_x + room.max_x) / 2),
    z: Math.floor((room.min_z + room.max_z) / 2)
  };
}

function centerBox(box) {
  return {
    x: Math.floor((box.min_x + box.max_x) / 2),
    z: Math.floor((box.min_z + box.max_z) / 2)
  };
}

function pointKey(point) {
  return `${point.x},${point.z}`;
}

function pairKeys(connects) {
  if (connects.length < 2) return [];
  return [pairKey(connects[0], connects[1]), pairKey(connects[1], connects[0])];
}

function pairKey(a, b) {
  return `${a}->${b}`;
}

function doorState(block = 'minecraft:dark_oak_door', facing, half, hinge) {
  let base = String(block).split('[')[0];
  if (!base.endsWith('_door')) base = 'minecraft:dark_oak_door';
  return `${base}[facing=${facing},half=${half},hinge=${hinge}]`;
}

function stairState(block = 'minecraft:spruce_stairs', facing) {
  let base = String(block).split('[')[0];
  if (!base.includes('stairs')) base = 'minecraft:spruce_stairs';
  return `${base}[facing=${facing},half=bottom]`;
}

function cell(block, module) {
  return { block, module };
}

function fillExteriorApproach(grid, materials, side, spanStart, spanEnd, outsideCoordinate, length) {
  const pathBlock = materials.path || 'minecraft:gravel';
  const steps = Math.max(1, length);
  if (side === 'south') {
    fillBox(grid, spanStart, 0, outsideCoordinate, spanEnd, 0, outsideCoordinate + steps - 1, pathBlock, 'entry_path');
    return { axis: 'z', from: { x: spanStart, z: outsideCoordinate }, to: { x: spanEnd, z: outsideCoordinate + steps - 1 }, length: steps };
  }
  if (side === 'north') {
    fillBox(grid, spanStart, 0, outsideCoordinate - steps + 1, spanEnd, 0, outsideCoordinate, pathBlock, 'entry_path');
    return { axis: 'z', from: { x: spanStart, z: outsideCoordinate - steps + 1 }, to: { x: spanEnd, z: outsideCoordinate }, length: steps };
  }
  if (side === 'east') {
    fillBox(grid, outsideCoordinate, 0, spanStart, outsideCoordinate + steps - 1, 0, spanEnd, pathBlock, 'entry_path');
    return { axis: 'x', from: { x: outsideCoordinate, z: spanStart }, to: { x: outsideCoordinate + steps - 1, z: spanEnd }, length: steps };
  }
  fillBox(grid, outsideCoordinate - steps + 1, 0, spanStart, outsideCoordinate, 0, spanEnd, pathBlock, 'entry_path');
  return { axis: 'x', from: { x: outsideCoordinate - steps + 1, z: spanStart }, to: { x: outsideCoordinate, z: spanEnd }, length: steps };
}

function exteriorApproachLength(spec = {}) {
  return clampInt(spec.garden_depth || spec.lot?.front_setback || 4, 3, 18, 4);
}

function clampInt(value, min, max, fallback = min) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(min, Math.min(max, Math.round(number)));
}
