import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { buildStage7Condition } from './coarseSemanticVoxelCondition.js';
import { deterministicCoarseSemanticVoxelProvider } from './coarseSemanticVoxelBaseline.js';
import { repairCoarseSemanticVoxelPlan } from './coarseSemanticVoxelRepair.js';
import { convertSemanticVoxelPlanToProceduralPlan } from './semanticVoxelProceduralPlan.js';
export const STAGE7_SHADOW_SOURCE='stage7-coarse-semantic-voxel-shadow-v1';
export const STAGE7_FAILURE_SOURCE='stage7-coarse-semantic-voxel-failure-v1';
export const MAX_STAGE7_ARTIFACT_BYTES=32*1024*1024;
export function createArtifactCoarseSemanticVoxelProvider({artifactPath}={}){return Object.freeze({id:'artifact',async generate({options={}}={}){return readArtifact(options.artifactPath||artifactPath);}})}
export function selectCoarseSemanticVoxelProvider(name,options={}){if(name==='baseline')return deterministicCoarseSemanticVoxelProvider;if(name==='artifact')return createArtifactCoarseSemanticVoxelProvider(options);throw new Error(`unsupported Milestone 1 coarse voxel provider: ${name}`)}
export async function runCoarseSemanticVoxelShadow({mode='off',provider='baseline',artifactPath,...rest}={}){if(mode==='off')return {source:STAGE7_SHADOW_SOURCE,active:false,mode:'off',provider:'baseline',status:'disabled',reason:'Stage 7 coarse voxel mode is off'};let condition,rawPlan,repair;let stage='condition';try{const input=rest;condition=buildStage7Condition(input);if(mode!=='shadow')throw Error(`unsupported Milestone 1 coarse voxel mode: ${mode}`);stage='provider';rawPlan=await selectCoarseSemanticVoxelProvider(provider,{artifactPath}).generate({condition,options:{artifactPath}});stage='semantic-validation';repair=repairCoarseSemanticVoxelPlan({plan:rawPlan,condition});if(!repair.accepted)return reject({mode,provider,condition,rawPlan,repair,stage});stage='conversion';const candidate=convertSemanticVoxelPlanToProceduralPlan({plan:repair.plan,condition,...rest});const result={source:STAGE7_SHADOW_SOURCE,active:true,mode,provider,status:'converted',condition,rawPlan,repairedPlan:{...structuredClone(repair.plan),derived_sketches:candidate.sketches},repair,candidate,providerProvenance:rawPlan.__stage7ArtifactProvenance||rawPlan.provider};return {...result,report:renderCoarseSemanticVoxelShadowReport(result)};}catch(error){return reject({mode,provider,condition,rawPlan,repair,stage,error,artifactPath})}}
export function compactCoarseSemanticVoxelShadow(r={}){if(!r.active)return undefined;return {source:r.source,active:true,mode:r.mode,provider:r.provider,status:r.status,condition_hash:r.condition?.condition_hash,artifact_sha256:r.providerProvenance?.sha256,raw_run_count:r.rawPlan?.runs?.length||0,repaired_run_count:r.repairedPlan?.runs?.length||0,repair_count:r.repair?.repairs?.length||0,blocker_count:r.repair?.blockers?.length||r.failureCase?.blockers?.length||0,warnings:r.warnings||[],fallback:r.status==='rejected'?'primary-build-unchanged':'not-needed'}}
export function renderCoarseSemanticVoxelShadowReport(r={}){return `# Stage 7 Milestone 1 Coarse Semantic Voxel Shadow\n\n- Status: ${r.status||'unknown'}\n\n## Semantic Layers\n\n## Reference Evidence\n\n## Conflicts\n\n## Conversion Decision\n`}
async function readArtifact(p){if(!p)throw Error('Stage 7 artifact provider requires an artifact path');const f=path.resolve(p);let s;try{s=await fs.stat(f)}catch(e){throw Error(`Could not read Stage 7 artifact: ${e.message}`)}if(s.size>MAX_STAGE7_ARTIFACT_BYTES)throw Error(`Stage 7 artifact exceeds ${MAX_STAGE7_ARTIFACT_BYTES} bytes`);const t=await fs.readFile(f,'utf8'),a={path:f,byte_size:s.size,sha256:createHash('sha256').update(t).digest('hex')};let v;try{v=JSON.parse(t)}catch(e){const x=Error(`Could not parse Stage 7 artifact: ${e.message}`);x.artifact={...a,malformed_excerpt:t.slice(0,4096)};throw x}Object.defineProperty(v,'__stage7ArtifactProvenance',{value:a});return v}
function reject({mode,provider,condition,rawPlan,repair,stage,error,artifactPath}){const failureCase={source:STAGE7_FAILURE_SOURCE,condition_hash:condition?.condition_hash,provider,failure_stage:stage,provider_error:error?.message,artifact:error?.artifact||(artifactPath?{path:path.resolve(artifactPath)}:undefined),blockers:repair?.blockers||[{id:'provider-or-converter-error',message:error?.message||'rejected'}],fallback:'primary-build-unchanged'};const r={source:STAGE7_SHADOW_SOURCE,active:true,mode,provider,status:'rejected',condition,rawPlan,repair,failureCase,warnings:error?[error.message]:[]};return {...r,report:renderCoarseSemanticVoxelShadowReport(r)}}
