import fs from 'node:fs/promises';
import path from 'node:path';
import { ensureDir, writeJson } from '../lib/fs.js';
import { clearCommandForBounds, commandForOperation } from '../lib/minecraftCommands.js';
import { resolveWorldDir } from '../lib/minecraftWorlds.js';
import { renderPreviewHtml } from '../render/previewHtml.js';
import { renderReport } from '../render/report.js';

export class ExportAgent {
  constructor({ outputDir, mcVersion = '1.21', minecraftDir, world, autoBuild = false }) {
    this.outputDir = outputDir;
    this.mcVersion = mcVersion;
    this.minecraftDir = minecraftDir;
    this.world = world;
    this.autoBuild = autoBuild;
  }

  async run({ prompt, requirement, originalRequirement, skill, plan, critique, repair, design, blueprint, validation }) {
    if (!validation.ok) {
      throw new Error(`Blueprint validation failed: ${validation.errors.join('; ')}`);
    }

    const datapackDir = path.join(this.outputDir, 'architect_datapack');
    const functionDir = path.join(datapackDir, 'data', 'architect', 'function');
    await ensureDir(functionDir);

    const commands = blueprint.operations.map(commandForOperation);
    const buildFunction = [
      '# Generated by Minecraft Architect Agent v1',
      '# Run with: /function architect:build',
      ...commands
    ].join('\n');
    const clearFunction = [
      '# Clear the generated build area',
      '# Run with: /function architect:clear',
      clearCommandForBounds(blueprint.bounds)
    ].join('\n');
    const autoBuildFunction = [
      '# Automatically called from architect:tick when --auto-build is enabled',
      'scoreboard players set #pending architect_state 0',
      'function architect:clear',
      'function architect:build',
      'tellraw @a [{"text":"AI Architect 自动建造完成。","color":"green"}]'
    ].join('\n');
    const loadFunction = [
      '# Generated by Minecraft Architect Agent v1',
      '# This prepares a one-shot automatic build on the next player tick.',
      'scoreboard objectives add architect_state dummy',
      'scoreboard players set #pending architect_state 1',
      'tellraw @a [{"text":"AI Architect 已加载，将在玩家位置自动建造。","color":"gold"}]'
    ].join('\n');
    const tickFunction = [
      '# Wait until a player is present, then build at that player position.',
      'execute if score #pending architect_state matches 1 as @a[limit=1,sort=nearest] at @s run function architect:auto_build'
    ].join('\n');

    const packMcmeta = {
      pack: {
        pack_format: 48,
        description: 'AI Minecraft Architect for Java 1.21'
      }
    };

    const blueprintPath = path.join(this.outputDir, 'blueprint.json');
    const packPath = path.join(datapackDir, 'pack.mcmeta');
    const buildPath = path.join(functionDir, 'build.mcfunction');
    const clearPath = path.join(functionDir, 'clear.mcfunction');
    const autoBuildPath = path.join(functionDir, 'auto_build.mcfunction');
    const loadPath = path.join(functionDir, 'load.mcfunction');
    const tickPath = path.join(functionDir, 'tick.mcfunction');
    const tagDir = path.join(datapackDir, 'data', 'minecraft', 'tags', 'function');
    const loadTagPath = path.join(tagDir, 'load.json');
    const tickTagPath = path.join(tagDir, 'tick.json');
    const rawPath = path.join(this.outputDir, 'raw_build.mcfunction');
    const previewPath = path.join(this.outputDir, 'preview.html');
    const reportPath = path.join(this.outputDir, 'run_report.md');

    await writeJson(blueprintPath, blueprint);
    await writeJson(packPath, packMcmeta);
    await fs.writeFile(buildPath, `${buildFunction}\n`, 'utf8');
    await fs.writeFile(clearPath, `${clearFunction}\n`, 'utf8');
    if (this.autoBuild) {
      await ensureDir(tagDir);
      await fs.writeFile(autoBuildPath, `${autoBuildFunction}\n`, 'utf8');
      await fs.writeFile(loadPath, `${loadFunction}\n`, 'utf8');
      await fs.writeFile(tickPath, `${tickFunction}\n`, 'utf8');
      await writeJson(loadTagPath, { values: ['architect:load'] });
      await writeJson(tickTagPath, { values: ['architect:tick'] });
    }
    await fs.writeFile(rawPath, `${commands.join('\n')}\n`, 'utf8');
    await fs.writeFile(previewPath, renderPreviewHtml({ prompt, design, blueprint, validation }), 'utf8');

    const installedDatapackDir = await this.installDatapack(datapackDir);

    await fs.writeFile(reportPath, renderReport({
      prompt,
      requirement,
      originalRequirement,
      skill,
      plan,
      critique,
      repair,
      design,
      blueprint,
      validation,
      artifacts: {
        datapackDir,
        buildPath,
        clearPath,
        rawPath,
        previewPath,
        installedDatapackDir
      },
      mcVersion: this.mcVersion,
      autoBuild: this.autoBuild
    }), 'utf8');

    return {
      blueprint: blueprintPath,
      datapackDir,
      buildFunction: buildPath,
      clearFunction: clearPath,
      rawBuild: rawPath,
      previewHtml: previewPath,
      report: reportPath,
      installedDatapackDir
    };
  }

  async installDatapack(datapackDir) {
    if (!this.world) return undefined;
    const worldDir = await resolveWorldDir({
      minecraftDir: this.minecraftDir,
      world: this.world
    });
    const targetDir = path.join(worldDir, 'datapacks', 'architect_datapack');
    await fs.rm(targetDir, { recursive: true, force: true });
    await ensureDir(path.dirname(targetDir));
    await fs.cp(datapackDir, targetDir, { recursive: true });
    return targetDir;
  }
}
