import fs from 'node:fs/promises';
import path from 'node:path';
import { ensureDir, writeJson } from '../lib/fs.js';
import { clearCommandForBounds, commandForOperation } from '../lib/minecraftCommands.js';
import { renderPreviewHtml } from '../render/previewHtml.js';
import { renderReport } from '../render/report.js';

export class ExportAgent {
  constructor({ outputDir, mcVersion = '1.21' }) {
    this.outputDir = outputDir;
    this.mcVersion = mcVersion;
  }

  async run({ prompt, requirement, design, blueprint, validation }) {
    if (!validation.ok) {
      throw new Error(`Blueprint validation failed: ${validation.errors.join('; ')}`);
    }

    const datapackDir = path.join(this.outputDir, 'architect_datapack');
    const functionDir = path.join(datapackDir, 'data', 'architect', 'function');
    await ensureDir(functionDir);

    const commands = blueprint.operations.map(commandForOperation);
    const buildFunction = [
      '# Generated by Minecraft Architect Agent v1',
      '# Run with: /function architect:build',
      ...commands
    ].join('\n');
    const clearFunction = [
      '# Clear the generated build area',
      '# Run with: /function architect:clear',
      clearCommandForBounds(blueprint.bounds)
    ].join('\n');

    const packMcmeta = {
      pack: {
        pack_format: 48,
        description: 'AI Minecraft Architect for Java 1.21'
      }
    };

    const blueprintPath = path.join(this.outputDir, 'blueprint.json');
    const packPath = path.join(datapackDir, 'pack.mcmeta');
    const buildPath = path.join(functionDir, 'build.mcfunction');
    const clearPath = path.join(functionDir, 'clear.mcfunction');
    const rawPath = path.join(this.outputDir, 'raw_build.mcfunction');
    const previewPath = path.join(this.outputDir, 'preview.html');
    const reportPath = path.join(this.outputDir, 'run_report.md');

    await writeJson(blueprintPath, blueprint);
    await writeJson(packPath, packMcmeta);
    await fs.writeFile(buildPath, `${buildFunction}\n`, 'utf8');
    await fs.writeFile(clearPath, `${clearFunction}\n`, 'utf8');
    await fs.writeFile(rawPath, `${commands.join('\n')}\n`, 'utf8');
    await fs.writeFile(previewPath, renderPreviewHtml({ prompt, design, blueprint, validation }), 'utf8');
    await fs.writeFile(reportPath, renderReport({
      prompt,
      requirement,
      design,
      blueprint,
      validation,
      artifacts: {
        datapackDir,
        buildPath,
        clearPath,
        rawPath,
        previewPath
      },
      mcVersion: this.mcVersion
    }), 'utf8');

    return {
      blueprint: blueprintPath,
      datapackDir,
      buildFunction: buildPath,
      clearFunction: clearPath,
      rawBuild: rawPath,
      previewHtml: previewPath,
      report: reportPath
    };
  }
}
