import fs from 'node:fs/promises';
import path from 'node:path';
import { ensureDir, writeJson } from '../lib/fs.js';
import { clearCommandForBounds, commandForOperation } from '../lib/minecraftCommands.js';
import { resolveWorldDir } from '../lib/minecraftWorlds.js';
import { renderPreviewHtml } from '../render/previewHtml.js';
import { renderReport } from '../render/report.js';

export class ExportAgent {
  constructor({ outputDir, mcVersion = '1.21', minecraftDir, world, datapacksDir, autoBuild = false }) {
    this.outputDir = outputDir;
    this.mcVersion = mcVersion;
    this.minecraftDir = minecraftDir;
    this.world = world;
    this.datapacksDir = datapacksDir;
    this.autoBuild = autoBuild;
  }

  async run({ prompt, requirement, originalRequirement, skill, plan, architecture, topology, critique, repair, design, blueprint, validation }) {
    if (!validation.ok) {
      throw new Error(`Blueprint validation failed: ${validation.errors.join('; ')}`);
    }

    const datapackDir = path.join(this.outputDir, 'architect_datapack');
    const functionDir = path.join(datapackDir, 'data', 'architect', 'function');
    await ensureDir(functionDir);

    const commands = blueprint.operations.map(commandForOperation);
    const buildFunction = [
      '# Generated by Minecraft Architect Agent v1',
      '# Run with: /function architect:build',
      ...commands
    ].join('\n');
    const clearFunction = [
      '# Clear the generated build area',
      '# Run with: /function architect:clear',
      clearCommandForBounds(blueprint.bounds)
    ].join('\n');
    const runFunction = [
      '# One-command build entrypoint',
      '# Run with: /function architect:run',
      '# /reload only refreshes the datapack and does not build.',
      'function architect:clear',
      'function architect:build',
      'tellraw @a [{"text":"AI Architect 建造完成。","color":"green"}]'
    ].join('\n');
    const packMcmeta = {
      pack: {
        pack_format: 48,
        description: 'AI Minecraft Architect for Java 1.21'
      }
    };

    const blueprintPath = path.join(this.outputDir, 'blueprint.json');
    const packPath = path.join(datapackDir, 'pack.mcmeta');
    const buildPath = path.join(functionDir, 'build.mcfunction');
    const clearPath = path.join(functionDir, 'clear.mcfunction');
    const runPath = path.join(functionDir, 'run.mcfunction');
    const rawPath = path.join(this.outputDir, 'raw_build.mcfunction');
    const previewPath = path.join(this.outputDir, 'preview.html');
    const reportPath = path.join(this.outputDir, 'run_report.md');

    await writeJson(blueprintPath, blueprint);
    await writeJson(packPath, packMcmeta);
    await fs.writeFile(buildPath, `${buildFunction}\n`, 'utf8');
    await fs.writeFile(clearPath, `${clearFunction}\n`, 'utf8');
    await fs.writeFile(runPath, `${runFunction}\n`, 'utf8');
    await fs.writeFile(rawPath, `${commands.join('\n')}\n`, 'utf8');
    await fs.writeFile(previewPath, renderPreviewHtml({ prompt, design, blueprint, validation }), 'utf8');

    const installedDatapackDir = await this.installDatapack(datapackDir);

    await fs.writeFile(reportPath, renderReport({
      prompt,
      requirement,
      originalRequirement,
      skill,
      plan,
      architecture,
      topology,
      critique,
      repair,
      design,
      blueprint,
      validation,
      artifacts: {
        datapackDir,
        buildPath,
        clearPath,
        runPath,
        rawPath,
        previewPath,
        installedDatapackDir
      },
      mcVersion: this.mcVersion,
      autoBuild: this.autoBuild
    }), 'utf8');

    return {
      blueprint: blueprintPath,
      datapackDir,
      buildFunction: buildPath,
      clearFunction: clearPath,
      runFunction: runPath,
      rawBuild: rawPath,
      previewHtml: previewPath,
      report: reportPath,
      installedDatapackDir
    };
  }

  async installDatapack(datapackDir) {
    if (this.datapacksDir) {
      const targetDir = path.join(path.resolve(this.datapacksDir), 'architect_datapack');
      await fs.rm(targetDir, { recursive: true, force: true });
      await ensureDir(path.dirname(targetDir));
      await fs.cp(datapackDir, targetDir, { recursive: true });
      return targetDir;
    }
    if (!this.world) return undefined;
    const worldDir = await resolveWorldDir({
      minecraftDir: this.minecraftDir,
      world: this.world
    });
    const targetDir = path.join(worldDir, 'datapacks', 'architect_datapack');
    await fs.rm(targetDir, { recursive: true, force: true });
    await ensureDir(path.dirname(targetDir));
    await fs.cp(datapackDir, targetDir, { recursive: true });
    return targetDir;
  }
}
