import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeStage7DatasetReviewPack } from './construction/learning/stage7DatasetReviewPack.js';
import { STAGE7_PILOT_CASE_IDS } from './construction/learning/stage7DatasetReviewOverlay.js';

export function parseStage7ReviewPackArgs(argv=[]) {
  const options={root:'mc_templates',knowledgeBase:'',out:'.tmp/stage7-m2-5-review-pack',caseIds:[],help:false};
  for (let index=0;index<argv.length;index+=1) {
    const flag=argv[index];
    if (flag==='--help') { options.help=true; continue; }
    if (flag==='--case') { const value=requireValue(argv,++index,flag); if (options.caseIds.includes(value)) throw new Error(`duplicate case id: ${value}`); options.caseIds.push(value); continue; }
    if (flag==='--root') { options.root=requireValue(argv,++index,flag); continue; }
    if (flag==='--knowledge-base') { options.knowledgeBase=requireValue(argv,++index,flag); continue; }
    if (flag==='--out') { options.out=requireValue(argv,++index,flag); continue; }
    throw new Error(`unknown Stage 7 review-pack option: ${flag}`);
  }
  return options;
}

export async function main(argv=process.argv.slice(2)) {
  const options=parseStage7ReviewPackArgs(argv);
  if (options.help) { console.log(helpText()); return; }
  const root=path.resolve(options.root);
  const result=await writeStage7DatasetReviewPack({
    templateRoot:root,knowledgeBasePath:options.knowledgeBase?path.resolve(options.knowledgeBase):path.join(root,'analysis','case_library.v2.json'),
    outputDir:path.resolve(options.out),caseIds:options.caseIds.length?options.caseIds:STAGE7_PILOT_CASE_IDS
  });
  console.log(`Stage 7 M2.5 review pack: ${result.outputDir}`);
  console.log(`Cases: ${result.index.case_count}`);
  console.log('Positive reviews generated by automation: 0');
}

function requireValue(argv,index,flag) { const value=argv[index]; if (!value||value.startsWith('--')) throw new Error(`${flag} requires a value`); return value; }
function helpText() { return `Usage: npm run review-pack:stage7 -- [options]\n\n  --root <path>\n  --knowledge-base <path>\n  --out <path>\n  --case <case-id>\n  --help`; }

const isMain=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);
if (isMain) main().catch((error)=>{console.error(error.message);process.exitCode=1;});
